### PR TITLE
Fix auditor

### LINKED ISSUE #191: auditor fails to parse valid image references
During the backfill https://github.com/kubernetes/k8s.io/pull/632, a buggy behavior was observed where the auditor could not parse certain image references.

The following images all triggered a `TRANSACTION REJECTED: could not determine source registry:` error:

```
gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller@sha256:050848d5a92c8c794af31726b982e8c29aff67e6043e9861e6c71d22d282aa6d
gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller@sha256:465842186bfa79cf037163d2c632f544bf8ef0f42065351e6fef7fca7ae58fde
gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller@sha256:6600f3e68b8139babd91d52339103c2f9cf0f61d87abcfb08140059047a05f50
gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller@sha256:cdf2581188c5de863f6e3bf3180c4d537e5bac25998ceb17f38076d7a28d08ad
gcr.io/k8s-artifacts-prod/cluster-api-aws/cluster-api-aws-controller@sha256:dc5d27778cb5e341d7703001e6009c34ddd89ddcdcf63efaf8edeef22b2aa8ee
gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:1dfec5637a7010d6c0955c26f0a752266fa2646ed2bf8e6ad745cdcfcb611db8
gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:435e92e8fa45c3bfadb2c12374ea5bea2173d1afbeff572cdca4ffee115a1be7
gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:bfd170a7683c58cb23c08a8ed3516fcfaa3180503be43a2be9a9deb0e1dfb0f2
gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:d3c06db4ef3ac9f309819e52a401ce2393aef76d2e9657e60daab9027c281855
gcr.io/k8s-artifacts-prod/e2e-test-images/agnhost@sha256:d9d5a169f27bac0c58cce541eeef3db7c2ddd70eca09b48da484a04564a6b1f9
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent@sha256:43273b274ee48f7fd7fc09bc82e7e75ddc596ca219fd9b522b1701bebec6ceff
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent@sha256:7bcbdf4cb26400ac576b33718000f0b630290dcf6380be3f60e33e5ba0461d31
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent@sha256:8735603bbd7153b8bfc8d2460481282bb44e2e830e5b237738e5c3e2a58c8f45
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent@sha256:99bade313218f3e6e63fdeb87bcddbf3a134aaa9e45e633be5ee5e60ddaac667
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent@sha256:c1ccf44d6b6fe49fc8506f7571f4a988ad69eb00c7747cd2b307b5e5b125a1f1
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server@sha256:101863ca4affcb2121b785ab34f87321a3f954dd2146ae7069eea87ce1bd7059
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server@sha256:504a5296bbe2d84b22bd15be13cc9cc0ef1c9f1f841ad1965bcf544d4f8246a0
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server@sha256:aa225a770fb144d26c341b0918cd35ca402658135b850f0857b88b4925e17426
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server@sha256:cecee42a9997c0ea06dfcaddfc6a940e4faf52ca31f8dc44f4e7e454c3c8d957
gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-server@sha256:e65695c53ad76b0b7c24e6df6954afbc6d7454197215149b29670af30304f26c
```

correction: the images are located in the `{asia,eu,us}` regions --- but they have been removed from the above paste for simplicity

### PR DESCRIPTION
**Pull request by listx**
This is first part of a couple more PRs to fix #191. I need to do this so that I can add unit tests for the `Audit()` function. After this PR I need to do a similar change (introduction of a wrapper type) for the `errorreporting.Client` stuff we still have in `Audit()`.

### CODE REVIEW

**Comment by listx** [comment]
/cc @justinsb @thockin @dims @bartsmykla 

Please take a look.

**Comment by listx** [comment]
For more context, I cannot currently add unit tests for the `Audit()` function because it has hardcoded dependencies on logging to actual GCP logs and also to Stackdriver Error Reporting on GCP. I need to remove the hard dependencies first before I can think about unit tests.

File: lib/logclient/fake.go [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+type FakeLogClient struct{}
+
+// Close is a NOP (there is nothing to close).
+func (fakeLogClient *FakeLogClient) Close() error { return nil }
+
+// NewFakeLoggingFacility returns a new LoggingFacility, but whose resources are
+// all local (stdout), with a FakeLogClient.
+func NewFakeLoggingFacility() *LoggingFacility {
+
+	logInfo := log.New(os.Stdout, "FAKE-INFO", log.LstdFlags)
```
Comment (justinsb) [inline lib/logclient/fake.go]: I know it's fake, but Stderr is normally the place for logs :-)

File: lib/logclient/gcp.go [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+// client are not split up over newlines, and also the severity levels are
+// actually understood by Stackdriver.
+func initGcpLogClient(projectID string) *logging.Client {
+
+	ctx := context.Background()
+
+	// Creates a client.
+	client, err := logging.NewClient(ctx, projectID)
+	if err != nil {
+		klog.Fatalf("Failed to create client: %v", err)
```
Comment (justinsb) [inline lib/logclient/gcp.go]: Nit: Looks like you could return the error, at least with the current code structure.  But I agree it's probably not worth it.

**Comment by justinsb** [comment]
Two minor nits that you can ignore, but lgtm

/approve
/lgtm

**Comment by listx** [comment]
Thanks for the review @justinsb !

I will address those nits in the next PR; merging this for now.

/hold cancel
